# Generated by Django 3.2.16 on 2022-12-06 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='module',
            field=models.CharField(choices=[('BGCHECK', 'BGCHECK')], default='BGCHECK', max_length=24),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when the session was created.')),
                ('end_date', models.DateTimeField(blank=True, help_text='Date and time when session was ended.', null=True)),
                ('active', models.BooleanField(default=False)),
                ('state', models.BinaryField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
