# Generated by Django 3.2.16 on 2022-12-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221206_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
