# Generated by Django 3.2.16 on 2022-12-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221210_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_user_bgcheck_value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
