# Generated by Django 3.2.16 on 2022-12-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_session_last_user_bgcheck_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='stop_session_flag',
            field=models.SmallIntegerField(blank=True, help_text='Signal for system that session should be stopped.', null=True),
        ),
    ]
